from django.conf.urls import url, include

from article.api import ArticleResource
article_resource = ArticleResource()


urlpatterns = [
    url(r'^all/$', 'article.views.articles'),
    url(r'^get/(?P<article_id>\d+)/$', 'article.views.article'),
    url(r'^create/$', 'article.views.create'),
    url(r'^add_comment/(?P<article_id>\d+)/$', 'article.views.add_comment'),
    url(r'^api/', include(article_resource.urls)),#Here is "urls". This is generated by "resource" automatically.
]